## <font color="maroon"> Importing the CEOs for whom the donations needs to be fetched </font>

In [4]:
import os
import numpy as np
import pandas as pd
os.chdir("D:\Sunny_Personal\OSU MSBA\Fall 2019\BehaviouralLab")
os.getcwd()
CEO_master=pd.read_excel("ceolistsample_pcsr.xlsx")

#Number of CEOs#
CEO_master.exec_fullname.nunique()

#Unique CEO list
CEO_unique=CEO_master.exec_fullname.unique()

#Creating a dataframe of unique CEO list
CEO_unique_pd=pd.DataFrame(CEO_unique)

#Replacing the garbage values
CEO_unique_pd[0]=CEO_unique_pd[0].str.replace(",","")
CEO_unique_pd[0]=CEO_unique_pd[0].str.replace(".","")
CEO_unique_pd[0]=CEO_unique_pd[0].str.replace("(","")
CEO_unique_pd[0]=CEO_unique_pd[0].str.replace(")","")
CEO_unique_pd[0]=CEO_unique_pd[0].str.replace(".","")
CEO_unique_pd[0]=CEO_unique_pd[0].str.replace(",","")

## <font color="maroon"> Extracting First Name and Last Name from the Name of CEO to create web URLs </font>
####  /*There are multiple combinations */

In [2]:
CEO_unique_pd['FirstName']=CEO_unique_pd[0].str.split('\s+').str[0]
CEO_unique_pd['LastName']=CEO_unique_pd[0].str.split('\s+').str[1]

CEO_unique_pd['FirstName1']=CEO_unique_pd[0].str.split('\s+').str[1]
CEO_unique_pd['LastName1']=CEO_unique_pd[0].str.split('\s+').str[0]

CEO_unique_pd['FirstName2']=CEO_unique_pd[0].str.split('\s+').str[0]
CEO_unique_pd['LastName2']=CEO_unique_pd[0].str.split('\s+').str[2]

CEO_unique_pd['FirstName3']=CEO_unique_pd[0].str.split('\s+').str[2]
CEO_unique_pd['LastName3']=CEO_unique_pd[0].str.split('\s+').str[0]

CEO_unique_pd['FirstName4']=CEO_unique_pd[0].str.split('\s+').str[0]
CEO_unique_pd['LastName4']=CEO_unique_pd[0].str.split('\s+').str[3]

CEO_unique_pd['FirstName5']=CEO_unique_pd[0].str.split('\s+').str[3]
CEO_unique_pd['LastName5']=CEO_unique_pd[0].str.split('\s+').str[0]


CEO_unique_pd['FirstName6']=CEO_unique_pd[0].str.split('\s+').str[1]
CEO_unique_pd['LastName6']=CEO_unique_pd[0].str.split('\s+').str[2]


CEO_unique_pd['FirstName7']=CEO_unique_pd[0].str.split('\s+').str[2]
CEO_unique_pd['LastName7']=CEO_unique_pd[0].str.split('\s+').str[1]


CEO_unique_pd['FirstName8']=CEO_unique_pd[0].str.split('\s+').str[1]
CEO_unique_pd['LastName8']=CEO_unique_pd[0].str.split('\s+').str[3]

CEO_unique_pd['FirstName9']=CEO_unique_pd[0].str.split('\s+').str[3]
CEO_unique_pd['LastName9']=CEO_unique_pd[0].str.split('\s+').str[1]


CEO_unique_pd['FirstName10']=CEO_unique_pd[0].str.split('\s+').str[2]
CEO_unique_pd['LastName10']=CEO_unique_pd[0].str.split('\s+').str[3]

CEO_unique_pd['FirstName11']=CEO_unique_pd[0].str.split('\s+').str[3]
CEO_unique_pd['LastName11']=CEO_unique_pd[0].str.split('\s+').str[2]

## <font color="maroon"> Concatenating firstName and LastName with +   ; Converting it to list to iterate </font>

In [6]:
CEO_unique_pd['token']=CEO_unique_pd['LastName'].map(str)+'+'+CEO_unique_pd['FirstName'].map(str)
CEO_unique_pd['token1']=CEO_unique_pd['LastName1'].map(str)+'+'+CEO_unique_pd['FirstName1'].map(str)
CEO_unique_pd['token2']=CEO_unique_pd['LastName2'].map(str)+'+'+CEO_unique_pd['FirstName2'].map(str)
CEO_unique_pd['token3']=CEO_unique_pd['LastName3'].map(str)+'+'+CEO_unique_pd['FirstName3'].map(str)
CEO_unique_pd['token4']=CEO_unique_pd['LastName4'].map(str)+'+'+CEO_unique_pd['FirstName4'].map(str)
CEO_unique_pd['token5']=CEO_unique_pd['LastName5'].map(str)+'+'+CEO_unique_pd['FirstName5'].map(str)
CEO_unique_pd['token6']=CEO_unique_pd['LastName6'].map(str)+'+'+CEO_unique_pd['FirstName6'].map(str)
CEO_unique_pd['token7']=CEO_unique_pd['LastName7'].map(str)+'+'+CEO_unique_pd['FirstName7'].map(str)
CEO_unique_pd['token8']=CEO_unique_pd['LastName8'].map(str)+'+'+CEO_unique_pd['FirstName8'].map(str)
CEO_unique_pd['token9']=CEO_unique_pd['LastName9'].map(str)+'+'+CEO_unique_pd['FirstName9'].map(str)
CEO_unique_pd['token10']=CEO_unique_pd['LastName10'].map(str)+'+'+CEO_unique_pd['FirstName10'].map(str)
CEO_unique_pd['token11']=CEO_unique_pd['LastName11'].map(str)+'+'+CEO_unique_pd['FirstName11'].map(str)


CEO_unique_pd_list0=CEO_unique_pd['token'].tolist()
CEO_unique_pd_list1=CEO_unique_pd['token1'].tolist()
CEO_unique_pd_list2=CEO_unique_pd['token2'].tolist()
CEO_unique_pd_list3=CEO_unique_pd['token3'].tolist()
CEO_unique_pd_list4=CEO_unique_pd['token4'].tolist()
CEO_unique_pd_list5=CEO_unique_pd['token5'].tolist()
CEO_unique_pd_list6=CEO_unique_pd['token6'].tolist()
CEO_unique_pd_list7=CEO_unique_pd['token7'].tolist()
CEO_unique_pd_list8=CEO_unique_pd['token8'].tolist()
CEO_unique_pd_list9=CEO_unique_pd['token9'].tolist()
CEO_unique_pd_list10=CEO_unique_pd['token10'].tolist()
CEO_unique_pd_list11=CEO_unique_pd['token11'].tolist()


#concatenating multiple lists to single one

CEO_unique_pd_list=CEO_unique_pd_list0+CEO_unique_pd_list1+CEO_unique_pd_list2+CEO_unique_pd_list3+CEO_unique_pd_list4+CEO_unique_pd_list5+CEO_unique_pd_list6+CEO_unique_pd_list7+CEO_unique_pd_list8+CEO_unique_pd_list9+CEO_unique_pd_list10+CEO_unique_pd_list11

# Deleting the Combinations with null values in either First Name or Last Name or both

In [21]:
CEO_unique_list_fin_trash2=[]

#removing elements that end with single letter
for i in   range(len(CEO_unique_pd_list)):
        if ( (CEO_unique_pd_list[i][-2]=='+')):
                CEO_unique_list_fin_trash2.append(CEO_unique_pd_list[i])
                del CEO_unique_pd_list[i]
                

#removing elements that start with single letter
for i in  range(len(CEO_unique_pd_list)):
        if ( (CEO_unique_pd_list[i][1]=='+')):
                CEO_unique_list_fin_trash2.append(CEO_unique_pd_list[i])
                del CEO_unique_pd_list[i]
                
for i in   range(len(CEO_unique_pd_list)):
        if ( (CEO_unique_pd_list[i][0:3]=='nan')):
                CEO_unique_list_fin_trash2.append(CEO_unique_pd_list[i])
                del CEO_unique_pd_list[i]
                
for i in  range(len(CEO_unique_pd_list)):
        if ( (CEO_unique_pd_list[i][-3:]=='nan')):
                CEO_unique_list_fin_trash2.append(CEO_unique_pd_list[i])
                del CEO_unique_pd_list[i]

# Scraping of donations using the URLs. CEO can have more than 200 donations ( 4*50 per page)

In [6]:
from selenium import webdriver
from bs4 imporat BeautifulSoup
import pandas as pd

#Configure chrome driver#
driver = webdriver.Chrome("chromedriver")

Notmapped_Donations=[]


for i in range(len(Not_Mapped_donations_pd_list1)):
    url= 'https://www.opensecrets.org/donor-lookup/results?name='+Not_Mapped_donations_pd_list1[i]
    print(url)
    for j in range(3):
        url_update=url+'&page='+str(j)
        print(url_update)
        driver.get(url_update)
        content = driver.page_source
        soup = BeautifulSoup(content)
        table_rows = soup.find_all('tr')

        for tr in table_rows:
            td = tr.find_all('td')
            row = [tr.text for tr in td]
            if row:
                Notmapped_Donations.append(row)

# Removing the duplicates and records with null donation amount

In [168]:
#Combination of str[0] & str[2] of scraped data with multiple combinations of master set
Donations=pd.DataFrame(Notmapped_Donations)
Donations.columns=['Category','Contributor','Occupation','Date_of_Donation','Amount','Recepient']
#dropping duplicates
Donations.drop_duplicates(None,keep='first',inplace=True)
#dropping records with null amount 
Donations=Donations.dropna(subset=['Amount'])
Donations['Contributor']=Donations['Contributor'].str.replace("\n","")
#Droppig columns
Donations=Donations.drop(['Recepient','Category'],axis=1)

Donations['LastName']=Donations.Contributor.str.split('\s+').str[2]
Donations['LastName']=Donations['LastName'].str.replace(",","")

Donations['FirstName']= Donations.Contributor.str.split('\s+').str[3]
Donations['FirstName']=Donations['FirstName'].str.replace(",","")
Donations['Year']=Donations['Date_of_Donation'].astype(str).str.split('-').str[2]
Donations=Donations[['LastName','FirstName','Year','Amount']]
Donations['Amount']=Donations['Amount'].str.replace("$","")
Donations['Amount']=Donations['Amount'].str.replace(",","")
Donations['Amount']=pd.to_numeric(Donations['Amount'])
Donations=Donations.groupby(['LastName','FirstName','Year'])['Amount'].sum()
Donations_fin=Donations.reset_index()
NotmappedDonations_final=Donations_fin

# Tagging the scraped donations to the CEOs

In [169]:
CEO_master=pd.read_excel("ceolistsample_pcsr.xlsx")

#merge1
Not_Mapped_donations_master=CEO_master

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[0]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[1]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes
Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes
NotmappedDonations_final.head()
Merged_data_new1=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])
Merged_data1=Merged_data_new1[Merged_data_new1['Amount'].notnull()]
Merged_data1

####################################################################################


#merge2
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[0]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[2]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new2=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])

Merged_data2=Merged_data_new2[Merged_data_new2['Amount'].notnull()]

###########################################################################



#merge3
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[0]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[3]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new3=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])

Merged_data3=Merged_data_new3[Merged_data_new3['Amount'].notnull()]

#########################################################################


#merge4
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[1]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[0]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new4=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])

Merged_data4=Merged_data_new4[Merged_data_new4['Amount'].notnull()]

################################################################################



#merge5
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[1]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[2]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new5=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])


Merged_data5=Merged_data_new5[Merged_data_new5['Amount'].notnull()]

#####################################################################################



#merge6
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[1]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[3]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new6=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])


Merged_data6=Merged_data_new6[Merged_data_new6['Amount'].notnull()]

######################################################################



#merge7
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[2]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[0]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new7=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])

Merged_data7=Merged_data_new7[Merged_data_new7['Amount'].notnull()]

###############################################################################



#merge7
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[2]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[1]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new8=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])


Merged_data8=Merged_data_new8[Merged_data_new8['Amount'].notnull()]

################################################################


#merge8
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[2]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[3]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new9=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])


Merged_data9=Merged_data_new9[Merged_data_new9['Amount'].notnull()]

###############################################################################



#merge10
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[3]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[0]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new10=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])

Merged_data10=Merged_data_new10[Merged_data_new10['Amount'].notnull()]

############################################################################
#merge11
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[3]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[1]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new11=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])

Merged_data11=Merged_data_new11[Merged_data_new11['Amount'].notnull()]

########################################################################


#merge12
#Not_Mapped_donations_master=pd.read_csv("not_Mapped_donations.csv")

Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[3]
Not_Mapped_donations_master['LastName']=Not_Mapped_donations_master['LastName'].str.replace(",","")
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.exec_fullname.str.split('\s+').str[2]
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master['FirstName'].str.replace(",","")
Not_Mapped_donations_master['LastName']= Not_Mapped_donations_master.LastName.str.upper()
Not_Mapped_donations_master['FirstName']= Not_Mapped_donations_master.FirstName.str.upper()
Not_Mapped_donations_master.rename(columns={"year": "Year"},inplace=True)
Not_Mapped_donations_master.dtypes

Not_Mapped_donations_master.columns
NotmappedDonations_final.columns
NotmappedDonations_final=NotmappedDonations_final[NotmappedDonations_final.Year.notnull()]
NotmappedDonations_final['Year']=NotmappedDonations_final.Year.astype('int64')
NotmappedDonations_final.dtypes

Merged_data_new12=pd.merge(Not_Mapped_donations_master[['Year','execid','id_gvkey','exec_fullname','coname','ceoann','ceo_flag','LastName','FirstName']],  
                   NotmappedDonations_final[['Year', 'Amount', 'LastName','FirstName']],  how='left',
                   on=['LastName','FirstName','Year'])

Merged_data12=Merged_data_new12[Merged_data_new12['Amount'].notnull()]




Merged_data04=pd.concat([Merged_data1,Merged_data2,Merged_data3,Merged_data4,Merged_data5,Merged_data6,Merged_data7,Merged_data8,Merged_data9,Merged_data10,Merged_data11,Merged_data12])
Merged_data04

,Year,execid,id_gvkey,exec_fullname,coname,ceoann,ceo_flag,LastName,FirstName,Amount
72,2002,20918,1161,Hector de Jesus Ruiz,ADVANCED MICRO DEVICES,CEO,1,HECTOR,DE,500.0
75,2005,20918,1161,Hector de Jesus Ruiz,ADVANCED MICRO DEVICES,CEO,1,HECTOR,DE,5000.0
76,2006,20918,1161,Hector de Jesus Ruiz,ADVANCED MICRO DEVICES,CEO,1,HECTOR,DE,5000.0
77,2007,20918,1161,Hector de Jesus Ruiz,ADVANCED MICRO DEVICES,CEO,1,HECTOR,DE,5000.0
99,2006,14660,1177,Ronald Allan Williams,AETNA INC,CEO,1,RONALD,ALLAN,1000.0
100,2007,14660,1177,Ronald Allan Williams,AETNA INC,CEO,1,RONALD,ALLAN,1000.0
101,2008,14660,1177,Ronald Allan Williams,AETNA INC,CEO,1,RONALD,ALLAN,1500.0
102,2009,14660,1177,Ronald Allan Williams,AETNA INC,CEO,1,RONALD,ALLAN,300.0
327,2000,13,1449,Daniel Paul Amos,AFLAC INC,CEO,1,DANIEL,PAUL,250.0
333,2006,13,1449,Daniel Paul Amos,AFLAC INC,CEO,1,DANIEL,PAUL,250.0
337,2010,13,1449,Daniel Paul Amos,AFLAC INC,CEO,1,DANIEL,PAUL,1250.0
338,2011,13,1449,Daniel Paul Amos,AFLAC INC,CEO,1,DANIEL,PAUL,250.0
340,2013,13,1449,Daniel Paul Amos,AFLAC INC,CEO,1,DANIEL,PAUL,250.0
342,2015,13,1449,Daniel Paul Amos,AFLAC INC,CEO,1,DANIEL,PAUL,250.0
343,2016,13,1449,Daniel Paul Amos,AFLAC INC,CEO,1,DANIEL,PAUL,1000.0
367,2002,14543,1478,Robert Alan Essner,WYETH,CEO,1,ROBERT,ALAN,2250.0
369,2004,14543,1478,Robert Alan Essner,WYETH,CEO,1,ROBERT,ALAN,2750.0
370,2005,14543,1478,Robert Alan Essner,WYETH,CEO,1,ROBERT,ALAN,500.0
371,2006,14543,1478,Robert Alan Essner,WYETH,CEO,1,ROBERT,ALAN,2350.0
392,2017,22916,1487,Brian Charles Duperreault,AMERICAN INTERNATIONAL GROUP,CEO,1,BRIAN,CHARLES,2629.0
617,2006,12438,1837,"John William Somerhalder, II",SOUTHERN CO GAS,CEO,1,JOHN,WILLIAM,2500.0
619,2008,12438,1837,"John William Somerhalder, II",SOUTHERN CO GAS,CEO,1,JOHN,WILLIAM,2300.0
623,2012,12438,1837,"John William Somerhalder, II",SOUTHERN CO GAS,CEO,1,JOHN,WILLIAM,250.0
624,2013,12438,1837,"John William Somerhalder, II",SOUTHERN CO GAS,CEO,1,JOHN,WILLIAM,250.0
1049,2009,12308,2312,"Harold Max Messmer, Jr.",ROBERT HALF INTL INC,CEO,1,HAROLD,MAX,500.0
1087,2008,2774,2403,James Milton Cornelius,BRISTOL-MYERS SQUIBB CO,CEO,1,JAMES,MILTON,1000.0
1088,2009,2774,2403,James Milton Cornelius,BRISTOL-MYERS SQUIBB CO,CEO,1,JAMES,MILTON,365.0
1181,2016,29332,2547,David Michael Cordani,CIGNA CORP,CEO,1,DAVID,MICHAEL,250.0
1190,2004,23192,2574,Michael Jon Ward,CSX CORP,CEO,1,MICHAEL,JON,1500.0
1191,2005,23192,2574,Michael Jon Ward,CSX CORP,CEO,1,MICHAEL,JON,500.0
...,...,...,...,...,...,...,...,...,...,...
1812,2004,2140,3505,"W. Leo Kiely, III",MOLSON COORS BREWING CO,CEO,1,III,LEO,2000.0
1813,2005,2140,3505,"W. Leo Kiely, III",MOLSON COORS BREWING CO,CEO,1,III,LEO,2100.0
1814,2006,2140,3505,"W. Leo Kiely, III",MOLSON COORS BREWING CO,CEO,1,III,LEO,5000.0
1815,2007,2140,3505,"W. Leo Kiely, III",MOLSON COORS BREWING CO,CEO,1,III,LEO,2000.0
6438,2001,3424,10426,"Kenneth Michael Jastrow, II",TEMPLE-INLAND INC,CEO,1,II,MICHAEL,800.0
6439,2002,3424,10426,"Kenneth Michael Jastrow, II",TEMPLE-INLAND INC,CEO,1,II,MICHAEL,400.0
6440,2003,3424,10426,"Kenneth Michael Jastrow, II",TEMPLE-INLAND INC,CEO,1,II,MICHAEL,800.0
6441,2004,3424,10426,"Kenneth Michael Jastrow, II",TEMPLE-INLAND INC,CEO,1,II,MICHAEL,239.0
6442,2005,3424,10426,"Kenneth Michael Jastrow, II",TEMPLE-INLAND INC,CEO,1,II,MICHAEL,400.0
6443,2006,3424,10426,"Kenneth Michael Jastrow, II",TEMPLE-INLAND INC,CEO,1,II,MICHAEL,2400.0
6444,2007,3424,10426,"Kenneth Michael Jastrow, II",TEMPLE-INLAND INC,CEO,1,II,MICHAEL,2000.0
6816,2010,27633,10920,"D. Scott Davis, CPA, CPA",UNITED PARCEL SERVICE INC,CEO,1,CPA,SCOTT,250.0
6817,2011,27633,10920,"D. Scott Davis, CPA, CPA",UNITED PARCEL SERVICE INC,CEO,1,CPA,SCOTT,250.0
6818,2012,27633,10920,"D. Scott Davis, CPA, CPA",UNITED PARCEL SERVICE INC,CEO,1,CPA,SCOTT,500.0
6819,2013,27633,10920,"D. Scott Davis, CPA, CPA",UNITED PARCEL SERVICE INC,CEO,1,CPA,SCOTT,500.0
7785,2008,30869,12756,"John Franklin Brock, III",COCA-COLA EUROPEAN PARTNERS,CEO,1,III,FRANKLIN,500.0
7787,2010,30869,12756,"John Franklin Brock, III",COCA-COLA EUROPEAN PARTNERS,CEO,1,III,FRANKLIN,500.0
7791,2014,30869,12756,"John Franklin Brock, III",COCA-COLA EUROPEAN PARTNERS,CEO,1,III,FRANKLIN,1000.0
8144,2010,29400,13988,"Walter William Bettinger, II",SCHWAB (CHARLES) CORP,CEO,1,II,WILLIAM,750.0
8149,2015,29400,13988,"Walter William Bettinger, II",SCHWAB (CHARLES) CORP,CEO,1,II,WILLIAM,500.0
8150,2016,29400,13988,"Walter William Bettinger, II",SCHWAB (CHARLES) CORP,CEO,1,II,WILLIAM,2000.0
9917,2007,10669,28349,"Thomas Joseph Wilson, II",ALLSTATE CORP,CEO,1,II,JOSEPH,2600.0
9918,2008,10669,28349,"Thomas Joseph Wilson, II",ALLSTATE CORP,CEO,1,II,JOSEPH,250.0
9919,2009,10669,28349,"Thomas Joseph Wilson, II",ALLSTATE CORP,CEO,1,II,JOSEPH,250.0
10674,2015,7269,61388,"Dominic James Addesso, CPA",EVEREST RE GROUP LTD,CEO,1,CPA,JAMES,250.0
11531,2013,39997,66446,"James Francis O'Neil, III",QUANTA SERVICES INC,CEO,1,III,FRANCIS,500.0
3385,2012,42519,5783,"John N. Roberts, III",HUNT (JB) TRANSPRT SVCS INC,CEO,1,III,ROBERTS,250.0
3389,2016,42519,5783,"John N. Roberts, III",HUNT (JB) TRANSPRT SVCS INC,CEO,1,III,ROBERTS,10000.0
9918,2008,10669,28349,"Thomas Joseph Wilson, II",ALLSTATE CORP,CEO,1,II,WILSON,250.0
11096,2017,35368,63605,"John B. Hill, III",CALPINE CORP,CEO,1,III,HILL,500.0

# Exporting the file to local system

In [170]:
Merged_data04.to_csv(r'D:\Sunny_Personal\OSU MSBA\Fall 2019\BehaviouralLab\mergeddata5.csv')